KNOWLEDGE_BASE = {
    "programs": {
        "pip": {
            "name": "Program Indonesia Pintar (PIP)",
            "agency": "Kemdikdasmen",
            "description": "Bantuan pendidikan untuk anak usia sekolah dari keluarga miskin/rentan",
            "url": "https://pip.kemdikbud.go.id",
            "keywords": ["pendidikan", "sekolah", "siswa", "miskin", "bantuan", "pip", "kip"],
            "requirements": ["KK", "KTP", "SKTM", "Terdaftar di DTKS"],
        },
        "kis": {
            "name": "Kartu Indonesia Sehat (KIS)",
            "agency": "BPJS Kesehatan",
            "description": "Jaminan kesehatan bagi masyarakat kurang mampu",
            "url": "https://bpjs-kesehatan.go.id",
            "keywords": ["kesehatan", "bpjs", "kis", "berobat", "rumah sakit"],
            "requirements": ["KK", "NIK"],
        },
        "bpnt": {
            "name": "Bantuan Pangan Non-Tunai (BPNT)",
            "agency": "Kemensos",
            "description": "Bantuan pangan untuk keluarga kurang mampu",
            "url": "https://kemensos.go.id",
            "keywords": ["pangan", "makanan", "sembako", "bansos", "bpnt"],
            "requirements": ["KK", "KTP", "Terdaftar di DTKS"],
        },
        "pkh": {
            "name": "Program Keluarga Harapan (PKH)",
            "agency": "Kemensos",
            "description": "Bantuan sosial bersyarat untuk keluarga miskin",
            "url": "https://pkh.kemensos.go.id",
            "keywords": ["keluarga", "bansos", "pkh", "ibu hamil", "balita"],
            "requirements": ["KK", "KTP", "Terdaftar di DTKS"],
        },
    },
    "documents": {
        "kk": {"name": "Kartu Keluarga", "issuer": "Dukcapil"},
        "ktp": {"name": "KTP Elektronik", "issuer": "Dukcapil"},
        "akte": {"name": "Akta Kelahiran", "issuer": "Dukcapil"},
        "sktm": {"name": "SKTM", "issuer": "Kelurahan"},
    },
}

TOPIC_CATEGORIES = {
    "greeting": {
        "keywords": ["halo", "hai", "hi", "hey", "pagi", "siang", "sore", "malam",
                      "selamat pagi", "selamat siang", "selamat sore", "selamat malam",
                      "apa kabar", "gimana kabar", "test", "tes", "coba", "hello", "hy",
                      "assalamualaikum", "assalamu alaikum"],
        "label": "Sapaan",
    },
    "kematian": {
        "keywords": ["meninggal", "meninggal dunia", "wafat", "tiada", "meninggalnya",
                      "almarhum", "almarhumah", "kematian", "ditinggal", "berduka"],
        "label": "Pengurusan Akta Kematian & Waris",
    },
    "pendidikan": {
        "keywords": ["kip", "pip", "sekolah", "pendidikan", "kuliah", "biaya sekolah",
                      "skhun", "ijazah", "beasiswa", "siswa", "mahasiswa", "belajar",
                      "universitas", "smk", "sma", "smp", "sd", "tk", "paud",
                      "bantuan pendidikan", "uang sekolah", "spp"],
        "label": "Bantuan Pendidikan",
    },
    "dokumen_hilang": {
        "keywords": ["ktp", "hilang", "kehilangan", "rusak", "ktp hilang", "ktp rusak",
                      "ganti ktp", "perpanjang ktp", "ektp"],
        "label": "Penggantian Dokumen Kependudukan",
    },
    "kesehatan": {
        "keywords": ["bpjs", "kis", "kesehatan", "berobat", "rumah sakit", "puskesmas",
                      "dokter", "sakit", "obat", "rs", "faskes", "rujukan", "bpjs kesehatan",
                      "jaminan kesehatan"],
        "label": "Layanan Kesehatan",
    },
    "bansos": {
        "keywords": ["bansos", "bantuan", "sembako", "pkh", "bpnt", "miskin", "fakir",
                      "keluarga miskin", "bantuan sosial", "bantuan pangan", "subsidi",
                      "blt", "bantuan langsung"],
        "label": "Bantuan Sosial",
    },
    "usaha": {
        "keywords": ["usaha", "kerja", "umkm", "wirausaha", "modal", "bisnis", "startup",
                      "usaha kecil", "usaha mikro", "nib", "izin usaha", "pelatihan kerja",
                      "lowongan", "pekerjaan"],
        "label": "Bantuan Usaha & Ketenagakerjaan",
    },
    "kk": {
        "keywords": ["kartu keluarga", "kk", "data keluarga", "anggota keluarga"],
        "label": "Pengurusan Kartu Keluarga",
    },
    "akte": {
        "keywords": ["akte", "akta kelahiran", "kelahiran", "lahir", "bayi", "anak", "akta"],
        "label": "Pembuatan Akta Kelahiran",
    },
    "pajak": {
        "keywords": ["pajak", "npwp", "spt", "pajak bumi", "pbb", "pajak kendaraan",
                      "pkb", "bpkb", "stnk", "pajak penghasilan"],
        "label": "Informasi Perpajakan",
    },
    "nikah": {
        "keywords": ["nikah", "menikah", "pernikahan", "kua", "suami", "istri", "kawin",
                      "catatan sipil"],
        "label": "Pendaftaran Pernikahan",
    },
    "pindah": {
        "keywords": ["pindah", "domisili", "pindah alamat", "pindah domisili",
                      "surat pindah", "merantau"],
        "label": "Pengurusan Pindah Domisili",
    },
    "perumahan": {
        "keywords": ["rumah", "perumahan", "subsidi rumah", "kpr", "btp",
                      "rumah subsidi", "rumah bersubsidi", "tempat tinggal"],
        "label": "Bantuan Perumahan",
    },
    "paspor": {
        "keywords": ["paspor", "imigrasi", "bepergian", "ke luar negeri", "visa", "perjalanan"],
        "label": "Pembuatan Paspor",
    },
    "sim": {
        "keywords": ["sim", "surat izin mengemudi", "mobil", "motor", "mengemudi",
                      "surat kendaraan"],
        "label": "Pembuatan SIM",
    },
    "listrik": {
        "keywords": ["listrik", "pln", "token listrik", "tagihan listrik",
                      "meteran listrik", "pasang listrik", "tambah daya"],
        "label": "Layanan Listrik",
    },
    "air": {
        "keywords": ["air", "pdam", "air bersih", "tagihan air", "air minum"],
        "label": "Layanan Air Bersih",
    },
    "sampah": {
        "keywords": ["sampah", "kebersihan", "dinas kebersihan", "limbah", "bank sampah",
                      "daur ulang"],
        "label": "Layanan Kebersihan",
    },
    "bencana": {
        "keywords": ["bencana", "banjir", "gempa", "longsor", "tsunami", "bencana alam",
                      "bpbd", "bnpb", "evakuasi", "pengungsian"],
        "label": "Penanganan Bencana",
    },
    "korupsi": {
        "keywords": ["korupsi", "lapor", "pengaduan", "kpk", "whistleblower",
                      "gratifikasi", "laporan", "aspirasi"],
        "label": "Layanan Pengaduan",
    },
    "sapawarga": {
        "keywords": ["sapa warga", "keluhan", "aspirasi", "laporan warga", "lapor",
                      "pengaduan masyarakat"],
        "label": "Aspirasi Warga",
    },
}

KNOWLEDGE_GRAPH_DATA = {
    "nodes": [
        {"id": "pip", "label": "Program Indonesia Pintar", "type": "program", "description": "Bantuan pendidikan untuk siswa kurang mampu"},
        {"id": "kip", "label": "Kartu Indonesia Pintar", "type": "program", "description": "Kartu identitas penerima PIP"},
        {"id": "kis", "label": "Kartu Indonesia Sehat", "type": "program", "description": "Jaminan kesehatan masyarakat"},
        {"id": "bpnt", "label": "Bantuan Pangan Non-Tunai", "type": "program", "description": "Bantuan pangan untuk keluarga miskin"},
        {"id": "pkh", "label": "Program Keluarga Harapan", "type": "program", "description": "Bantuan sosial bersyarat"},
        {"id": "kemendikdasmen", "label": "Kemdikdasmen", "type": "agency", "description": "Kementerian Pendidikan Dasar dan Menengah"},
        {"id": "kemensos", "label": "Kemensos RI", "type": "agency", "description": "Kementerian Sosial RI"},
        {"id": "bpjs", "label": "BPJS Kesehatan", "type": "agency", "description": "Badan Penyelenggara Jaminan Sosial"},
        {"id": "dukcapil", "label": "Ditjen Dukcapil", "type": "agency", "description": "Direktorat Jenderal Kependudukan dan Pencatatan Sipil"},
        {"id": "kk", "label": "Kartu Keluarga", "type": "document", "description": "Dokumen identitas keluarga"},
        {"id": "ktp", "label": "KTP Elektronik", "type": "document", "description": "Kartu Tanda Penduduk elektronik"},
        {"id": "akte", "label": "Akta Kelahiran", "type": "document", "description": "Dokumen kelahiran"},
        {"id": "sktm", "label": "SKTM", "type": "document", "description": "Surat Keterangan Tidak Mampu"},
        {"id": "bantuan_pendidikan", "label": "Bantuan Pendidikan", "type": "benefit", "description": "Dana bantuan untuk biaya pendidikan"},
        {"id": "bantuan_kesehatan", "label": "Bantuan Kesehatan", "type": "benefit", "description": "Akses layanan kesehatan gratis"},
        {"id": "bantuan_pangan", "label": "Bantuan Pangan", "type": "benefit", "description": "Bantuan kebutuhan pangan"},
        {"id": "kantor_kelurahan", "label": "Kantor Kelurahan", "type": "location", "description": "Kantor pelayanan kelurahan"},
        {"id": "kecamatan", "label": "Kantor Kecamatan", "type": "location", "description": "Kantor pelayanan kecamatan"},
        {"id": "dtks", "label": "DTKS", "type": "requirement", "description": "Terdaftar di Data Terpadu Kesejahteraan Sosial"},
        {"id": "nik", "label": "Memiliki NIK", "type": "requirement", "description": "Nomor Induk Kependudukan valid"},
    ],
    "links": [
        {"source": "pip", "target": "kemendikdasmen", "label": "dikelola oleh"},
        {"source": "kip", "target": "pip", "label": "bagian dari"},
        {"source": "pip", "target": "bantuan_pendidikan", "label": "memberikan"},
        {"source": "kis", "target": "bpjs", "label": "dikelola oleh"},
        {"source": "kis", "target": "bantuan_kesehatan", "label": "memberikan"},
        {"source": "bpnt", "target": "kemensos", "label": "dikelola oleh"},
        {"source": "bpnt", "target": "bantuan_pangan", "label": "memberikan"},
        {"source": "pkh", "target": "kemensos", "label": "dikelola oleh"},
        {"source": "kk", "target": "dukcapil", "label": "diterbitkan oleh"},
        {"source": "ktp", "target": "dukcapil", "label": "diterbitkan oleh"},
        {"source": "pip", "target": "kk", "label": "membutuhkan"},
        {"source": "pip", "target": "ktp", "label": "membutuhkan"},
        {"source": "pip", "target": "sktm", "label": "membutuhkan"},
        {"source": "pip", "target": "dtks", "label": "memerlukan"},
        {"source": "pip", "target": "nik", "label": "memerlukan"},
        {"source": "kis", "target": "kk", "label": "membutuhkan"},
        {"source": "kis", "target": "nik", "label": "memerlukan"},
        {"source": "bpnt", "target": "kk", "label": "membutuhkan"},
        {"source": "bpnt", "target": "ktp", "label": "membutuhkan"},
        {"source": "pkh", "target": "dtks", "label": "memerlukan"},
        {"source": "pkh", "target": "kk", "label": "membutuhkan"},
        {"source": "pip", "target": "kis", "label": "terkait"},
        {"source": "pkh", "target": "bpnt", "label": "dapat digabung dengan"},
    ],
}
