[theme]
primaryColor = "#a78bfa"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#151828"
textColor = "#FFFFFF"
font = "sans serif"

[server]
maxUploadSize = 10
enableXsrfProtection = false
enableCORS = true

[browser]
gatherUsageStats = false
